### PR TITLE
ES6 plus

### PR DESCRIPTION
**Pull request by fundon**
* use `const` instead of `let`
* destructuring
* formatting

### CODE REVIEW

**Comment by abe33** [comment]
I'm curious, are there any measurable benefits from using const instead of let? (I'm not talking about theorical stuff but actual measures in Atom)

Also, I don't want to be too harsh, but I'd rather see you working on the various remaining issues than nitpicking on coding styles. As you probably noticed, I added `standard` as linter instead of `eslint` for [this reason](https://www.npmjs.com/package/standard#i-disagree-with-rule-x-can-you-change-it).
Do you work on windows by any change? There're several issues that would need some investigations.

**Comment by fundon** [comment]
I'm working on Mac.

Why using `const` instead of `let`?
They are practically the same speed. Perhaps const is slightly faster.
The Node.js Project is switching to const.

Currently, We use Babel to compile the codes, and do not disable the `es6.constants` flag on Babel-v5.x, So there are nothing for measurable benefits.

**Comment by fundon** [comment]
Should we refactor the travis-ci and be compatible with Windows or Linux?

**Comment by abe33** [comment]
> Should we refactor the travis-ci and be compatible with Windows or Linux?

That would be great indeed, but I fear it won't help with the issue at hand. The most important one is related to parts of the minimap not rendered properly (empty), I actually tried that on two windows device I have at work or at home but I can't reproduce it.
Another one is related with screen scaling on windows (which can gives `devicePixelRatio` such `1.25`, and makes the minimap all blurry), and this time the devices I have access to doesn't support this feature so I can't just test it.

**Comment by abe33** [comment]
Also, I have a PR waiting for new optimizations, and I see that your PR is still failing, so if I find that the changes in my PR really gives good results I'll probably merge it before yours. I hope we won't have too much conflicts. I'll also probably take some time to make the new code use const and space in destructuring so that you don't need to make a second pass on that code.

**Comment by fundon** [comment]
Ok, I'll review it. 👍

**Comment by fundon** [comment]
> Another one is related with screen scaling on windows (which can gives devicePixelRatio such 1.25, and makes the minimap all blurry)

How about an option for `devicePixelRatio` ? Or Sets the `devicePixelRatio` to 2 by force.

**Pull request closed without merging**
