### PR TITLE
Fix for #314 - end drag when alttabed away from atom

### LINKED ISSUE #314: Bad behavior if alt-tabbed away while dragging the minimap
See [this](https://github.com/atom-minimap/minimap/commit/d4c02dfb73cda0b852f25720776bb151802407ee#commitcomment-10665515) comment.

Reproduction steps:

1. Have two panes with two open files (each with its own minimap)
2. Click and drag the minimap on the first pane
3. While dragging, alt tab away from atom
4. Repeat 2 and 3 one more time
5. Click and drag the minimap on the second pane
6. Both panes scroll instead of just the second.

Doing steps 1 and 2 again might toggle the behavior again.
Additionally, if one adds a logging message to `endDrag()`, we can observe it being called at strange times, including when selecting arbitrary text.

### PR DESCRIPTION
**Pull request by ChaoticMind**
This fixes #314, with some reservations that may or may not matter:

1. This fix doesn't let us comment out the event handlers on `mouseleave`
2. I'm not sure if the `onblur` event should be on document.body or on the minimap element
3. Not sure how to write specs for this :)

### CODE REVIEW

**Comment by ChaoticMind** [comment]
Looks like the tests that were failing locally are now also failing in Travis.

**Comment by abe33** [comment]
It's actually a good news if travis is failing now. I'll take a look at how I can make the test less dependant on these kind of hard coded values.

**Comment by abe33** [comment]
2: I suggest you use `addEventListener` instead of `onblur`, the latter means that each views erase the listener of the previous one, and you can't really dispose it. As for the event target, neither on the body nor on the minimap, but on the window (as mentioned in the SO answer, mixing document and window events is one of the worst idea of jQuery and had confused more than one dev). For the minimap element, as it doesn't have a tabindex, it can't be focused.
3: Just like with the `mouseleave` test (https://github.com/atom-minimap/minimap/blob/master/spec/minimap-element-spec.coffee#L366-L373) except you'll have to dispatch a `blur` event on the window instead.

**Comment by abe33** [comment]
I'll close given it have been opened for more that one year without any change.

**Comment by ChaoticMind** [comment]
Oh, I hadn't realized this was still open/pending. I'll reopen if/when I end up improving it. Thanks for the tips.

**Pull request closed without merging**
