### PR TITLE
Fix leak minimap

### PR DESCRIPTION
**Pull request by aki77**
## repro steps

[Gyazo](http://gyazo.com/36ce9286db7753bbc39f9844a0d81fc5)

[Gyazo](http://gyazo.com/c5e3f507e35433aa603ea800f79ce967)

###  after correction

[Gyazo](http://gyazo.com/e92d07682ec9a0e22b4114a0e889f9ad)

### CODE REVIEW

**Comment by abe33** [comment]
Thank you for taking care of that, I'll take time to review that tonight.

**Comment by abe33** [comment]
Was published in v4.11.1

**Comment by aki77** [comment]
Thanks!

**Comment by aki77** [comment]
Please see.

https://github.com/atom-minimap/minimap-git-diff/pull/15

**Pull request merged**
