### PR TITLE
Fix independent minimap scroll

### PR DESCRIPTION
**Pull request by abe33**

### CODE REVIEW

**Comment by mehcode** [comment]
@abe33 Why do we need this [relayMousewheelEvent](https://github.com/atom-minimap/minimap/blob/0552856ae4250557a43bcd6dd58e84df9e24545e/lib/minimap-element.js#L1134) method?

If you instead `event.stopPropagation` conditional to `scrollIndependentlyOnMouseWheel` then you could remove the whole method from my testing. Is this used in another way I don't see? I'm definitely still new to the code base.

See https://github.com/mehcode/atom-minimap-plus/commit/3f3370ababf8b05e499be5397a329a783d6636ed

**Comment by abe33** [comment]
Initially it was because the editor was listening for mouse within its shadow DOM, so mousewheeling over the minimap was not triggering an editor scroll so we had to relay these events. I didn't noticed that in the meantime they had changed that part, so you're right it's no longer needed.

**Comment by abe33** [comment]
I'll be merging and publishing a patch as a lot of users have issues with it right now

**Comment by mehcode** [comment]
Thanks for explaining that @abe33 ; glad to see it fixed.

**Pull request merged**
