### PR TITLE
Fix display problem when in vim-mode-plus's normal mode

### LINKED ISSUE #532: Minimap doesn't work when Vim Mode's Normal mode enabled
I use vim-mode-plus and as I mentioned in the title when I switch to normal mode, minimap disappears. Also, absolute mode enabled.

**Minimap:** 4.25.6
**Atom:** 1.11.2

### PR DESCRIPTION
**Pull request by kutsan**
This resolves #532.

### CODE REVIEW

**Comment by fundon** [comment]
Which theme does you use?

**Comment by Kutsan** [comment]
@fundon atom-material-ui with atom-material-syntax-dark

**Comment by fundon** [comment]
@kustan I tried and not found that.

I recommend that taking it to your `styles.less`.

**Comment by Kutsan** [comment]
Here is my [style.less](https://github.com/Kutsan/dotfiles/blob/master/.atom/styles.less).

**Pull request closed without merging**
