### PR TITLE
feat: warn about poor performance if treesitter is off

### PR DESCRIPTION
**Pull request by aminya**
The performance of Minimap with and without Tree-sitter is like night and day. We should inform the users about this, so they can have the best experience with Minimap.

### CODE REVIEW

**Comment by blueedgetechno** [comment]
Atleast provide a option to suppress the warning, its annoying everytime I open Atom.

**Comment by aminya** [comment]
It only warns once a day not every time.

**Comment by blueedgetechno** [comment]
That's weird coz I received everytime untill I manually edited the package locally to stop it.

**Comment by aminya** [comment]
Run this in the dev tools to reset the day calculator. You should receive warnings once a day.
```
window.localStorage.removeItem("Minimap.core.useTreeSitterParsers")
```

**Comment by blueedgetechno** [comment]
Thanks I will try this if the problem persists.

**Pull request merged**
