### PR TITLE
Fix conflict with docblock-python

### PR DESCRIPTION
**Pull request by maky-hnou**
This pull request will fix the issue #693

### CODE REVIEW

**Review by aminya — COMMENTED** [review]
I can't reproduce this. What's the reproduction?

**Comment by UziTech** [comment]
It seems like this was an issue in an older version of atom

**Comment by aminya** [comment]
The patch is OK because the logic is correct. However, the issue does not exist anymore.

**Comment by UziTech** [comment]
I would leave it as is without this PR. if it happens again we can figure out exactly why.

**Comment by aminya** [comment]
I changed it, so it is not destructive. I think this is safe to merge now.

**Comment by UziTech** [comment]
the `atom.views.getView(minimap)` is technically the same as `this.minimapViewProvider(minimap)` because of the [`viewProvider`](https://github.com/atom-minimap/minimap/blob/master/package.json#L44-L46)

**Comment by UziTech** [comment]
This seems unnecessary. Just slows it down with extra checks. Unless we can figure out the actual problem I don't think it is worth it.

**Comment by aminya** [comment]
OK. I will keep this PR open, just in case.

**Comment by UziTech** [comment]
This was a problem with docblock-python and should be fixed there.

https://github.com/spadarian/docblock-python/issues/43#issuecomment-739114791

**Pull request closed without merging**
