### PR TITLE
fix: use StyleReader from atom-ide-base

### PR DESCRIPTION
**Pull request by aminya**
- Uses StyleReader form atom-ide-base
- Removes some of the deprecated functions

### CODE REVIEW

**Review by aminya — COMMENTED** [review]
The tests pass locally
image

**Comment by UziTech** [comment]
It is failing for me locally. looks like `minimapElement.StyleReader` is undefined in the tests.

**Comment by aminya** [comment]
This is fixed now.

**Review by UziTech — APPROVED** [review]
Unfortunately until https://github.com/atom/atom/issues/22650 is fixed semantic release won't work

**Comment by aminya** [comment]
That's fine. We can defer the release

**Pull request merged**
